### ISSUE TITLE
Autodetect libraries

### ISSUE THREAD

**Issue by jkbest2** [cbedwards-dfw/namespacify#1]
This package looks great! I had a couple ideas for additional features and wanted to write them down before I forget them. Definitely no pressure to do anything with these ideas. If I have some time I might hack on them a bit at some point.

The first idea is to scan all of the script files to be `namespacify`d and use anything that looks like a `library(package)` or `require(package)` to populate the list of packages. Probably best off as a separate function that can then feed into the `namespacify_*` functions.

**Comment by cbedwards-dfw** [comment]
I really like this! It sounds like you're suggesting a function that returns the list of suggested packages, which users can then add provide in the `packages` argument? I think a semi-manual approach like this is probably best, since there's the potential for unnecessary library calls in scripts. I certainly have scripts with "ghost" library calls for packages I ended up not using.
